build:
  image: node
  commands:
    - npm i --dev
    - npm install -g casperjs
    - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    - tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2
    - mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
    - npm test
  environment:
    - ENV=development
    - STEAM_KEY=$$STEAM_KEY
    - STEAM_RETURN=$$STEAM_RETURN
    - STEAM_REALM=$$STEAM_REALM
    - STEAM_PASS=$$STEAM_PASS
    - COUCH_USER=$$COUCH_USER
    - COUCH_PASS=$$COUCH_PASS
    - KEEN_ID=$$KEEN_ID
    - KEEN_WRITE=$$KEEN_WRITE
    - COOKIE=$$COOKIE


compose:
  database:
    image: couchdb
